import 'dotenv/config';
import { randomBytes, scrypt } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const envPath = resolve('.env.local');
const handoffPath = resolve('.auth-credentials.txt');
const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

function randomPassword() {
  return `${randomBytes(9).toString('base64url')}!${randomBytes(9).toString('base64url')}9a`;
}

function base32(bytes: Buffer) {
  let bits = '';
  for (const byte of bytes) bits += byte.toString(2).padStart(8, '0');
  let result = '';
  for (let index = 0; index < bits.length; index += 5) result += alphabet[Number.parseInt(bits.slice(index, index + 5).padEnd(5, '0'), 2)];
  return result;
}

function hashPassword(password: string) {
  const salt = randomBytes(16);
  return new Promise<string>((resolveHash, reject) => {
    scrypt(password.normalize('NFKC'), salt, 64, { cost: 131072, blockSize: 8, parallelization: 1, maxmem: 256 * 1024 * 1024 }, (error, key) => {
      if (error) reject(error);
      else resolveHash(`scrypt$131072$8$1$${salt.toString('base64url')}$${key.toString('base64url')}`);
    });
  });
}

function upsertEnvironment(source: string, values: Record<string, string>) {
  const keys = new Set([...Object.keys(values), 'ADMIN_DEFAULT_PASSWORD']);
  const retained = source.split(/\r?\n/).filter((line) => !keys.has(line.split('=', 1)[0].trim()));
  const generated = Object.entries(values).map(([key, value]) => `${key}=${JSON.stringify(value)}`);
  return `${retained.join('\n').trim()}\n\n# Secure staff authentication (generated by npm run auth:provision)\n${generated.join('\n')}\n`;
}

async function main() {
  const existing = await readFile(envPath, 'utf8');
  if (/^AUTH_SECRET=/m.test(existing) && !process.argv.includes('--rotate')) {
    throw new Error('Authentication is already provisioned. Use --rotate to replace every credential and invalidate access after existing sessions expire.');
  }

  const adminPasswordMatch = existing.match(/^ADMIN_DEFAULT_PASSWORD\s*=\s*["']?([^"'\r\n]+)["']?\s*$/m);
  const adminPassword = adminPasswordMatch?.[1] || randomPassword();
  const ceoPassword = randomPassword();
  const adminEmail = 'admin@mosobalajeimports.ng';
  const ceoEmail = 'ceo@mosobalajeimports.ng';
  const adminTotp = base32(randomBytes(20));
  const ceoTotp = base32(randomBytes(20));
  const portalSlug = randomBytes(32).toString('base64url');
  const appUrlMatch = existing.match(/^APP_URL\s*=\s*["']?([^"'\r\n]+)["']?\s*$/m);
  const appUrl = (appUrlMatch?.[1] || 'http://localhost:3000').replace(/\/$/, '');

  const values = {
    AUTH_SECRET: randomBytes(48).toString('base64url'),
    AUTH_ADMIN_EMAIL: adminEmail,
    AUTH_ADMIN_PASSWORD_HASH: await hashPassword(adminPassword),
    AUTH_ADMIN_TOTP_SECRET: adminTotp,
    AUTH_CEO_EMAIL: ceoEmail,
    AUTH_CEO_PASSWORD_HASH: await hashPassword(ceoPassword),
    AUTH_CEO_TOTP_SECRET: ceoTotp,
    CEO_PORTAL_SLUG: portalSlug,
  };

  await writeFile(envPath, upsertEnvironment(existing, values), { encoding: 'utf8', mode: 0o600 });
  await writeFile(handoffPath, [
    'Mosobalaje authentication bootstrap credentials',
    'Store these in a password manager, enroll both TOTP secrets, then permanently delete this file.',
    '',
    `Admin URL: ${appUrl}/admin/sign-in`,
    `Admin email: ${adminEmail}`,
    `Admin password: ${adminPassword}`,
    `Admin authenticator secret: ${adminTotp}`,
    '',
    `Private CEO URL: ${appUrl}/${portalSlug}`,
    `CEO email: ${ceoEmail}`,
    `CEO password: ${ceoPassword}`,
    `CEO authenticator secret: ${ceoTotp}`,
    '',
  ].join('\n'), { encoding: 'utf8', mode: 0o600 });

  console.log('Authentication provisioned. Credentials were written to .auth-credentials.txt and were not printed.');
}

main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
